name: IMAC
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - matplotlib-base=3.5.1
  - pandas=1.4.2
  - numpy
  - ipywidgets=7.7.2
  - jupyterlab>=3.1
  - voila>=0.2.16
  - jupyterlab-widgets  # Ensures compatibility with ipywidgets
  - widgetsnbextension  # Ensures Jupyter Notebook compatibility
